version: '3'
services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - "0.0.0.0:3333:3333"
    volumes:
      - .:/usr/app
    # network_mode: host
volumes:
  pgdata:
    driver: local
